// flow-typed signature: e6b845b032c8d6ab8590ec9a7c8d70a9
// flow-typed version: <<STUB>>/@fortawesome/fontawesome-pro_v^5.10.2/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/fontawesome-pro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/fontawesome-pro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/fontawesome-pro/js/all' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/all.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/brands' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/brands.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/conflict-detection' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/conflict-detection.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/duotone' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/duotone.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/fontawesome' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/fontawesome.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/light' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/light.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/regular' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/regular.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/solid' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/solid.min' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/v4-shims' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-pro/js/v4-shims.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/fontawesome-pro/js/all.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/all'>;
}
declare module '@fortawesome/fontawesome-pro/js/all.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/all.min'>;
}
declare module '@fortawesome/fontawesome-pro/js/brands.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/brands'>;
}
declare module '@fortawesome/fontawesome-pro/js/brands.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/brands.min'>;
}
declare module '@fortawesome/fontawesome-pro/js/conflict-detection.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/conflict-detection'>;
}
declare module '@fortawesome/fontawesome-pro/js/conflict-detection.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/conflict-detection.min'>;
}
declare module '@fortawesome/fontawesome-pro/js/duotone.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/duotone'>;
}
declare module '@fortawesome/fontawesome-pro/js/duotone.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/duotone.min'>;
}
declare module '@fortawesome/fontawesome-pro/js/fontawesome.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/fontawesome'>;
}
declare module '@fortawesome/fontawesome-pro/js/fontawesome.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/fontawesome.min'>;
}
declare module '@fortawesome/fontawesome-pro/js/light.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/light'>;
}
declare module '@fortawesome/fontawesome-pro/js/light.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/light.min'>;
}
declare module '@fortawesome/fontawesome-pro/js/regular.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/regular'>;
}
declare module '@fortawesome/fontawesome-pro/js/regular.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/regular.min'>;
}
declare module '@fortawesome/fontawesome-pro/js/solid.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/solid'>;
}
declare module '@fortawesome/fontawesome-pro/js/solid.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/solid.min'>;
}
declare module '@fortawesome/fontawesome-pro/js/v4-shims.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/v4-shims'>;
}
declare module '@fortawesome/fontawesome-pro/js/v4-shims.min.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-pro/js/v4-shims.min'>;
}
