projects:
  zenport:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        dev:
          url: 'https://graphql-staging.zenport.io/graphql'
          subscription: 'https://graphql-staging.zenport.io/graphql'
          introspect: true
