####################################
# Branch develop deploy to staging #
####################################
name: 'Deploy Staging'
triggers:
  - branches: ['develop']
steps:
  - name: 'node:10-slim'
    entrypoint: yarn
    args:
      ['install', '--non-interactive', '--no-progress', '--frozen-lockfile', '--ignore-optional']
  - name: 'node:10-slim'
    entrypoint: yarn
    args: ['build:stg']
    env: ['ZENPORT_FIREBASE_DEPLOY_REVISION=$SHORT_SHA']
  - name: 'gcr.io/zenport-183806/firebase'
    args: ['deploy', '--only', 'hosting:staging']
    secretEnv: ['FIREBASE_TOKEN']
  - name: 'gcr.io/zenport-183806/firebase'
    args: ['database:set', '/revision_staging', '--data', '"$SHORT_SHA"', '--confirm']
    secretEnv: ['FIREBASE_TOKEN']
secrets:
  # - kmsKeyName: 'projects/zenport-183806/locations/global/keyRings/testkeyring/cryptoKeys/firebase-token'
  - kmsKeyName: 'projects/zenport-183806/locations/global/keyRings/cloudbuild/cryptoKeys/FIREBASE_TOKEN'
    secretEnv:
      # FIREBASE_TOKEN: 'CiQAKjLYag9heOEXkyV+2/1LczLNEo4AOWWmpARIZU0CraWhx5QSkAEAIxlCYzpTudu+QIRZExou5TZrvrSKjKSqwJEMrslWMcBOUxbOw7mUkmOb/2BajUYUmU70yKg6H2bgXhAKmhsoEs2f6K3Uze6TT2zs+AU72AHcea9yGCffvhe6Sm1KBM1n055Ln1hf0yYnB7xhpu958brz/WN/W5QzX0bT6LaldUjM4fSuCyW2TMH2gXQxBLU='
      FIREBASE_TOKEN: 'CiQABMiRSxFPfnwdM7ahaPi95H2ma5VUVYCgwx3zI9ZhWFOQ81oSkAEA9/U/J4HRwK9t0kLVe6F1T1W74JWV3AEPQ14N6aDa99NnGln6D3E6W+ZuSMEX1dwkUbG9UulC6Y/9swER5SzggPkAmHIKHaQnp1u1VpXoML1qMG1iRo8qCfbyJsTBfmXxYcnpkaJPwT9JAtHamX3maDhdnU2C80sVD+iys1WlL8Lm1I1xoItc0Z/E9VpIzXM='
timeout: 2400s
---
#########################################
# Branch hotfixes deploy to staging-hot #
#########################################
name: 'Deploy Staging Hotfixes'
triggers:
  - branches: ['hotfixes']
steps:
  - name: 'node:10-slim'
    entrypoint: yarn
    args:
      ['install', '--non-interactive', '--no-progress', '--frozen-lockfile', '--ignore-optional']
  - name: 'node:10-slim'
    entrypoint: yarn
    args: ['build:stg']
    env:
      - 'ZENPORT_FIREBASE_DEPLOY_REVISION=$SHORT_SHA'
      - 'ZENPORT_FIREBASE_REVISION_KEY=revision_staging_hot'
  - name: 'gcr.io/zenport-183806/firebase'
    args: ['deploy', '--only', 'hosting:staging-hot']
    secretEnv: ['FIREBASE_TOKEN']
  - name: 'gcr.io/zenport-183806/firebase'
    args: ['database:set', '/revision_staging_hot', '--data', '"$SHORT_SHA"', '--confirm']
    secretEnv: ['FIREBASE_TOKEN']
secrets:
  - kmsKeyName: 'projects/zenport-183806/locations/global/keyRings/cloudbuild/cryptoKeys/FIREBASE_TOKEN'
    secretEnv:
      FIREBASE_TOKEN: 'CiQABMiRS2pzGQzkQpV9nxSXoJ2JJasJwnByeP5/LkT1BvD480USVgBl1o1Vk8mKYamYIoTV+nKp3ioXT69W8uWUke0duMu48TPBE2kNHEU6lDETMssT8Mw7rPaATUsLDb69WA5MhmvpdXHz2nOavdjM9ZfWa/ZoV9Bcvp83'
timeout: 1800s
---
######################################
# Branch master deploy to production #
######################################
name: 'Deploy Prod'
triggers:
  - branches: ['master']
steps:
  - name: 'node:10-slim'
    entrypoint: yarn
    args:
      ['install', '--non-interactive', '--no-progress', '--frozen-lockfile', '--ignore-optional']
  - name: 'node:10-slim'
    entrypoint: yarn
    args: ['build:prod']
    env: ['ZENPORT_FIREBASE_DEPLOY_REVISION=$SHORT_SHA']
  - name: 'gcr.io/zenport-183806/firebase'
    args: ['deploy', '--only', 'hosting:prod']
    secretEnv: ['FIREBASE_TOKEN']
  - name: 'gcr.io/zenport-183806/firebase'
    args: ['database:set', '/revision_production', '--data', '"$SHORT_SHA"', '--confirm']
    secretEnv: ['FIREBASE_TOKEN']
secrets:
  - kmsKeyName: 'projects/zenport-183806/locations/global/keyRings/cloudbuild/cryptoKeys/FIREBASE_TOKEN'
    secretEnv:
      FIREBASE_TOKEN: 'CiQABMiRS2pzGQzkQpV9nxSXoJ2JJasJwnByeP5/LkT1BvD480USVgBl1o1Vk8mKYamYIoTV+nKp3ioXT69W8uWUke0duMu48TPBE2kNHEU6lDETMssT8Mw7rPaATUsLDb69WA5MhmvpdXHz2nOavdjM9ZfWa/ZoV9Bcvp83'
timeout: 1800s
