name: 'Linter'
on:
  pull_request:
    branches:
      - develop
      - hotfixes

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: yarn flow
