// @flow

export const Actions = {
  INIT: 'init',
  APPEND: 'append',
  REARRANGE: 'rearrange',
  CELL_UPDATE: 'cell_update',
  CHANGE_VALUES: 'change_values',
  REPLACE_ITEM: 'replace_item',
  DELETE_ITEM: 'delete_item',
  SET_ERRORS: 'set_errors',
  FOCUS: 'focus',
  FOCUS_UP: 'focus_up',
  FOCUS_DOWN: 'focus_down',
  FOCUS_RIGHT: 'focus_right',
  FOCUS_LEFT: 'focus_left',
  BLUR: 'blur',
  FOREIGN_FOCUSES: 'foreign_focuses',
  FOREIGN_FOCUS: 'foreign_focus',
  FOREIGN_BLUR: 'foreign_blur',
  ADDED_ROWS_OF_ENTITY: 'added_rows_of_entity',
  CLEAR_ADDED_ROWS: 'clear_added_rows',
  REMOVED_ROWS_ENTITY: 'removed_rows_of_entity',
  CLEAR_REMOVED_ROWS: 'clear_removed_rows',
};
