// flow-typed signature: 8cabca4e172263f69153e59f2b08ab4c
// flow-typed version: <<STUB>>/apollo-upload-client_v^11.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-upload-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-upload-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-upload-client/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-upload-client/lib/index' {
  declare module.exports: $Exports<'apollo-upload-client/lib'>;
}
declare module 'apollo-upload-client/lib/index.js' {
  declare module.exports: $Exports<'apollo-upload-client/lib'>;
}
