// flow-typed signature: eacf69bc7f9b615be7afad09b2857425
// flow-typed version: <<STUB>>/hotkeys-js_v^3.7.2/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hotkeys-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hotkeys-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hotkeys-js/dist/hotkeys.common' {
  declare module.exports: any;
}

declare module 'hotkeys-js/dist/hotkeys.common.min' {
  declare module.exports: any;
}

declare module 'hotkeys-js/dist/hotkeys.esm' {
  declare module.exports: any;
}

declare module 'hotkeys-js/dist/hotkeys' {
  declare module.exports: any;
}

declare module 'hotkeys-js/dist/hotkeys.min' {
  declare module.exports: any;
}

declare module 'hotkeys-js/doc/website.990e6ef2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hotkeys-js/dist/hotkeys.common.js' {
  declare module.exports: $Exports<'hotkeys-js/dist/hotkeys.common'>;
}
declare module 'hotkeys-js/dist/hotkeys.common.min.js' {
  declare module.exports: $Exports<'hotkeys-js/dist/hotkeys.common.min'>;
}
declare module 'hotkeys-js/dist/hotkeys.esm.js' {
  declare module.exports: $Exports<'hotkeys-js/dist/hotkeys.esm'>;
}
declare module 'hotkeys-js/dist/hotkeys.js' {
  declare module.exports: $Exports<'hotkeys-js/dist/hotkeys'>;
}
declare module 'hotkeys-js/dist/hotkeys.min.js' {
  declare module.exports: $Exports<'hotkeys-js/dist/hotkeys.min'>;
}
declare module 'hotkeys-js/doc/website.990e6ef2.js' {
  declare module.exports: $Exports<'hotkeys-js/doc/website.990e6ef2'>;
}
declare module 'hotkeys-js/index' {
  declare module.exports: $Exports<'hotkeys-js'>;
}
declare module 'hotkeys-js/index.js' {
  declare module.exports: $Exports<'hotkeys-js'>;
}
