// flow-typed signature: 9e738c8bbd20a6bd5129eb6691946000
// flow-typed version: <<STUB>>/match-sorter_v^4.0.1/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'match-sorter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'match-sorter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'match-sorter/dist/match-sorter.cjs' {
  declare module.exports: any;
}

declare module 'match-sorter/dist/match-sorter.esm' {
  declare module.exports: any;
}

declare module 'match-sorter/dist/match-sorter.umd' {
  declare module.exports: any;
}

declare module 'match-sorter/dist/match-sorter.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'match-sorter/dist/match-sorter.cjs.js' {
  declare module.exports: $Exports<'match-sorter/dist/match-sorter.cjs'>;
}
declare module 'match-sorter/dist/match-sorter.esm.js' {
  declare module.exports: $Exports<'match-sorter/dist/match-sorter.esm'>;
}
declare module 'match-sorter/dist/match-sorter.umd.js' {
  declare module.exports: $Exports<'match-sorter/dist/match-sorter.umd'>;
}
declare module 'match-sorter/dist/match-sorter.umd.min.js' {
  declare module.exports: $Exports<'match-sorter/dist/match-sorter.umd.min'>;
}
