// flow-typed signature: cda74dc009016ef7ab043fed9e5b4ec4
// flow-typed version: <<STUB>>/number-precision_v^1.3.1/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'number-precision'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'number-precision' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'number-precision/build-test/src' {
  declare module.exports: any;
}

declare module 'number-precision/build/index.iife' {
  declare module.exports: any;
}

declare module 'number-precision/build' {
  declare module.exports: any;
}

declare module 'number-precision/build/index.umd' {
  declare module.exports: any;
}

declare module 'number-precision/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'number-precision/build-test/src/index' {
  declare module.exports: $Exports<'number-precision/build-test/src'>;
}
declare module 'number-precision/build-test/src/index.js' {
  declare module.exports: $Exports<'number-precision/build-test/src'>;
}
declare module 'number-precision/build/index.iife.js' {
  declare module.exports: $Exports<'number-precision/build/index.iife'>;
}
declare module 'number-precision/build/index' {
  declare module.exports: $Exports<'number-precision/build'>;
}
declare module 'number-precision/build/index.js' {
  declare module.exports: $Exports<'number-precision/build'>;
}
declare module 'number-precision/build/index.umd.js' {
  declare module.exports: $Exports<'number-precision/build/index.umd'>;
}
declare module 'number-precision/rollup.config.js' {
  declare module.exports: $Exports<'number-precision/rollup.config'>;
}
