// flow-typed signature: 1983d97bc1008b2b12f3b6eae4832d35
// flow-typed version: <<STUB>>/pluralize_v^8.0.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pluralize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pluralize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pluralize/pluralize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pluralize/pluralize.js' {
  declare module.exports: $Exports<'pluralize/pluralize'>;
}
