// flow-typed signature: 10c2b869b574b1f13d0bb30d86057849
// flow-typed version: <<STUB>>/randomcolor_v^0.5.4/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'randomcolor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'randomcolor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'randomcolor/randomColor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'randomcolor/randomColor.js' {
  declare module.exports: $Exports<'randomcolor/randomColor'>;
}
