// flow-typed signature: 5048aa29e2af83046379e0e507cb5dd7
// flow-typed version: <<STUB>>/react-draggable_v^4.1.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-draggable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-draggable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-draggable/build/cjs/cjs' {
  declare module.exports: any;
}

declare module 'react-draggable/build/cjs/Draggable' {
  declare module.exports: any;
}

declare module 'react-draggable/build/cjs/DraggableCore' {
  declare module.exports: any;
}

declare module 'react-draggable/build/cjs/utils/domFns' {
  declare module.exports: any;
}

declare module 'react-draggable/build/cjs/utils/getPrefix' {
  declare module.exports: any;
}

declare module 'react-draggable/build/cjs/utils/log' {
  declare module.exports: any;
}

declare module 'react-draggable/build/cjs/utils/positionFns' {
  declare module.exports: any;
}

declare module 'react-draggable/build/cjs/utils/shims' {
  declare module.exports: any;
}

declare module 'react-draggable/build/cjs/utils/types' {
  declare module.exports: any;
}

declare module 'react-draggable/build/Draggable' {
  declare module.exports: any;
}

declare module 'react-draggable/build/DraggableCore' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/cjs' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/Draggable' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/DraggableCore' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/utils/domFns' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/utils/getPrefix' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/utils/log' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/utils/positionFns' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/utils/shims' {
  declare module.exports: any;
}

declare module 'react-draggable/build/module/utils/types' {
  declare module.exports: any;
}

declare module 'react-draggable/build/umd' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/domFns' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/getPrefix' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/log' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/positionFns' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/shims' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/types' {
  declare module.exports: any;
}

declare module 'react-draggable/build/web/react-draggable.min' {
  declare module.exports: any;
}

declare module 'react-draggable/web/react-draggable.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-draggable/build/cjs/cjs.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/cjs'>;
}
declare module 'react-draggable/build/cjs/Draggable.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/Draggable'>;
}
declare module 'react-draggable/build/cjs/DraggableCore.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/DraggableCore'>;
}
declare module 'react-draggable/build/cjs/utils/domFns.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/utils/domFns'>;
}
declare module 'react-draggable/build/cjs/utils/getPrefix.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/utils/getPrefix'>;
}
declare module 'react-draggable/build/cjs/utils/log.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/utils/log'>;
}
declare module 'react-draggable/build/cjs/utils/positionFns.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/utils/positionFns'>;
}
declare module 'react-draggable/build/cjs/utils/shims.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/utils/shims'>;
}
declare module 'react-draggable/build/cjs/utils/types.js' {
  declare module.exports: $Exports<'react-draggable/build/cjs/utils/types'>;
}
declare module 'react-draggable/build/Draggable.js' {
  declare module.exports: $Exports<'react-draggable/build/Draggable'>;
}
declare module 'react-draggable/build/DraggableCore.js' {
  declare module.exports: $Exports<'react-draggable/build/DraggableCore'>;
}
declare module 'react-draggable/build/module/cjs.js' {
  declare module.exports: $Exports<'react-draggable/build/module/cjs'>;
}
declare module 'react-draggable/build/module/Draggable.js' {
  declare module.exports: $Exports<'react-draggable/build/module/Draggable'>;
}
declare module 'react-draggable/build/module/DraggableCore.js' {
  declare module.exports: $Exports<'react-draggable/build/module/DraggableCore'>;
}
declare module 'react-draggable/build/module/utils/domFns.js' {
  declare module.exports: $Exports<'react-draggable/build/module/utils/domFns'>;
}
declare module 'react-draggable/build/module/utils/getPrefix.js' {
  declare module.exports: $Exports<'react-draggable/build/module/utils/getPrefix'>;
}
declare module 'react-draggable/build/module/utils/log.js' {
  declare module.exports: $Exports<'react-draggable/build/module/utils/log'>;
}
declare module 'react-draggable/build/module/utils/positionFns.js' {
  declare module.exports: $Exports<'react-draggable/build/module/utils/positionFns'>;
}
declare module 'react-draggable/build/module/utils/shims.js' {
  declare module.exports: $Exports<'react-draggable/build/module/utils/shims'>;
}
declare module 'react-draggable/build/module/utils/types.js' {
  declare module.exports: $Exports<'react-draggable/build/module/utils/types'>;
}
declare module 'react-draggable/build/umd.js' {
  declare module.exports: $Exports<'react-draggable/build/umd'>;
}
declare module 'react-draggable/build/utils/domFns.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/domFns'>;
}
declare module 'react-draggable/build/utils/getPrefix.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/getPrefix'>;
}
declare module 'react-draggable/build/utils/log.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/log'>;
}
declare module 'react-draggable/build/utils/positionFns.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/positionFns'>;
}
declare module 'react-draggable/build/utils/shims.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/shims'>;
}
declare module 'react-draggable/build/utils/types.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/types'>;
}
declare module 'react-draggable/build/web/react-draggable.min.js' {
  declare module.exports: $Exports<'react-draggable/build/web/react-draggable.min'>;
}
declare module 'react-draggable/web/react-draggable.min.js' {
  declare module.exports: $Exports<'react-draggable/web/react-draggable.min'>;
}
