// flow-typed signature: fdc01407ed8e53317fdc1d91da694dfb
// flow-typed version: <<STUB>>/react-draggable_v^4.0.3/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-draggable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-draggable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-draggable/build/Draggable' {
  declare module.exports: any;
}

declare module 'react-draggable/build/DraggableCore' {
  declare module.exports: any;
}

declare module 'react-draggable/build/umd' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/domFns' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/getPrefix' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/log' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/positionFns' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/shims' {
  declare module.exports: any;
}

declare module 'react-draggable/build/utils/types' {
  declare module.exports: any;
}

declare module 'react-draggable/web/react-draggable.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-draggable/build/Draggable.js' {
  declare module.exports: $Exports<'react-draggable/build/Draggable'>;
}
declare module 'react-draggable/build/DraggableCore.js' {
  declare module.exports: $Exports<'react-draggable/build/DraggableCore'>;
}
declare module 'react-draggable/build/umd.js' {
  declare module.exports: $Exports<'react-draggable/build/umd'>;
}
declare module 'react-draggable/build/utils/domFns.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/domFns'>;
}
declare module 'react-draggable/build/utils/getPrefix.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/getPrefix'>;
}
declare module 'react-draggable/build/utils/log.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/log'>;
}
declare module 'react-draggable/build/utils/positionFns.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/positionFns'>;
}
declare module 'react-draggable/build/utils/shims.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/shims'>;
}
declare module 'react-draggable/build/utils/types.js' {
  declare module.exports: $Exports<'react-draggable/build/utils/types'>;
}
declare module 'react-draggable/index' {
  declare module.exports: $Exports<'react-draggable'>;
}
declare module 'react-draggable/index.js' {
  declare module.exports: $Exports<'react-draggable'>;
}
declare module 'react-draggable/web/react-draggable.min.js' {
  declare module.exports: $Exports<'react-draggable/web/react-draggable.min'>;
}
