// flow-typed signature: 36fccd8d4abfb75dcf13043e9eeba843
// flow-typed version: <<STUB>>/react-svg_v^10.0.25/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg/dist' {
  declare module.exports: any;
}

declare module 'react-svg/dist/react-svg.cjs.development' {
  declare module.exports: any;
}

declare module 'react-svg/dist/react-svg.cjs.production' {
  declare module.exports: any;
}

declare module 'react-svg/dist/react-svg.esm' {
  declare module.exports: any;
}

declare module 'react-svg/dist/react-svg.umd.development' {
  declare module.exports: any;
}

declare module 'react-svg/dist/react-svg.umd.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg/dist/index' {
  declare module.exports: $Exports<'react-svg/dist'>;
}
declare module 'react-svg/dist/index.js' {
  declare module.exports: $Exports<'react-svg/dist'>;
}
declare module 'react-svg/dist/react-svg.cjs.development.js' {
  declare module.exports: $Exports<'react-svg/dist/react-svg.cjs.development'>;
}
declare module 'react-svg/dist/react-svg.cjs.production.js' {
  declare module.exports: $Exports<'react-svg/dist/react-svg.cjs.production'>;
}
declare module 'react-svg/dist/react-svg.esm.js' {
  declare module.exports: $Exports<'react-svg/dist/react-svg.esm'>;
}
declare module 'react-svg/dist/react-svg.umd.development.js' {
  declare module.exports: $Exports<'react-svg/dist/react-svg.umd.development'>;
}
declare module 'react-svg/dist/react-svg.umd.production.js' {
  declare module.exports: $Exports<'react-svg/dist/react-svg.umd.production'>;
}
