// flow-typed signature: 43da1cd336fbd80e2baeb8f9ebe39c96
// flow-typed version: <<STUB>>/react-fullstory_v^1.3.2/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fullstory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fullstory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fullstory/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-fullstory/dist/index.esm' {
  declare module.exports: any;
}

declare module 'react-fullstory/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fullstory/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-fullstory/dist/index.cjs'>;
}
declare module 'react-fullstory/dist/index.esm.js' {
  declare module.exports: $Exports<'react-fullstory/dist/index.esm'>;
}
declare module 'react-fullstory/dist/index' {
  declare module.exports: $Exports<'react-fullstory/dist'>;
}
declare module 'react-fullstory/dist/index.js' {
  declare module.exports: $Exports<'react-fullstory/dist'>;
}
