// flow-typed signature: fb53fd13af552431383ddeaf8d1cbf1f
// flow-typed version: <<STUB>>/react-hotkeys_v^2.0.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hotkeys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hotkeys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hotkeys/cjs/configure' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/AltedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/AltShiftedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/EventResponse' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/KeyEventSequenceIndex' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/KeyEventState' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/KeyEventType' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/KeyOSAndLayoutAliasesDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/KeyShorthandDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/KeysWithKeyUpHiddenByCmd' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/ModifierFlagsDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/MousetrapToReactKeyNamesDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/NonPrintableKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/reverse-dictionaries/UnaltedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/reverse-dictionaries/UnaltShiftedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/reverse-dictionaries/UnshiftedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/const/ShiftedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/deprecatedWithHotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/getApplicationKeyMap' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/GlobalHotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/logging/describeKeyEvent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/logging/describeKeyEventType' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/logging/printComponent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/isCmdKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/isCustomKeyName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/isNonPrintableKeyName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/isValidKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/standardizeKeyName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/stateFromEvent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/applicableAliasFunctions' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/getKeyName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/hasKeyPressEvent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/isFromFocusOnlyComponent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/keyupIsHiddenByCmd' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveAltedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveAltShiftedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveKeyAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveShiftedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnaltedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnaltShiftedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnshiftedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/HotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/IgnoreKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/config/Configuration' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/definitions/ComponentOptionsList' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/definitions/ComponentOptionsListIterator' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/definitions/ComponentTree' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/KeyEventManager' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/listening/EventPropagator' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/listening/KeyCombination' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/listening/KeyEventCounter' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/listening/KeyHistory' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/logging/Logger' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/matching/ActionResolver' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/matching/KeyCombinationMatcher' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/matching/KeyHistoryMatcher' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/shared/KeyCombinationSerializer' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/shared/KeyEventStateArrayManager' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/shared/KeySequenceParser' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/shared/Registry' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/strategies/AbstractKeyEventStrategy' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/strategies/FocusOnlyKeyEventStrategy' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/lib/strategies/GlobalKeyEventStrategy' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/ObserveKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/react-hotkeys.production.min' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/recordKeyCombination' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/array/arrayFrom' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/array/indexFromEnd' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/array/removeAtIndex' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/backwardsCompatibleContext' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/collection/contains' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/collection/isEmpty' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/collection/size' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/collection/without' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/invertArrayDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/isUndefined' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/object/copyAttributes' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/object/dictionaryFrom' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/object/hasKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/object/isObject' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/string/capitalize' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/string/isString' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/string/normalizeEventName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/utils/string/stripSuperfluousWhitespace' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/vendor/react-dom/getEventCharCode' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/vendor/react-dom/reactsGetEventKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/vendor/react-dom/translateToKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/withHotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/withHotKeysIgnoreOverride' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/withIgnoreKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/cjs/withObserveKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/configure' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/AltedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/AltShiftedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/EventResponse' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/KeyEventSequenceIndex' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/KeyEventState' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/KeyEventType' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/KeyOSAndLayoutAliasesDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/KeyShorthandDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/KeysWithKeyUpHiddenByCmd' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/ModifierFlagsDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/MousetrapToReactKeyNamesDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/NonPrintableKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/reverse-dictionaries/UnaltedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/reverse-dictionaries/UnaltShiftedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/reverse-dictionaries/UnshiftedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/const/ShiftedKeysDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/deprecatedWithHotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/getApplicationKeyMap' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/GlobalHotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/logging/describeKeyEvent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/logging/describeKeyEventType' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/logging/printComponent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/parsing-key-maps/isCmdKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/parsing-key-maps/isCustomKeyName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/parsing-key-maps/isNonPrintableKeyName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/parsing-key-maps/isValidKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/parsing-key-maps/standardizeKeyName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/parsing-key-maps/stateFromEvent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/applicableAliasFunctions' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/getKeyName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/hasKeyPressEvent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/isFromFocusOnlyComponent' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/keyupIsHiddenByCmd' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveAltedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveAltShiftedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveKeyAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveShiftedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveUnaltedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveUnaltShiftedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveUnshiftedAlias' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/HotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/IgnoreKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/config/Configuration' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/definitions/ComponentOptionsList' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/definitions/ComponentOptionsListIterator' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/definitions/ComponentTree' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/KeyEventManager' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/listening/EventPropagator' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/listening/KeyCombination' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/listening/KeyEventCounter' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/listening/KeyHistory' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/logging/Logger' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/matching/ActionResolver' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/matching/KeyCombinationMatcher' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/matching/KeyHistoryMatcher' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/shared/KeyCombinationSerializer' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/shared/KeyEventStateArrayManager' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/shared/KeySequenceParser' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/shared/Registry' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/strategies/AbstractKeyEventStrategy' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/strategies/FocusOnlyKeyEventStrategy' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/lib/strategies/GlobalKeyEventStrategy' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/ObserveKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/react-hotkeys.production.min' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/recordKeyCombination' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/array/arrayFrom' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/array/indexFromEnd' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/array/removeAtIndex' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/backwardsCompatibleContext' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/collection/contains' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/collection/isEmpty' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/collection/size' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/collection/without' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/invertArrayDictionary' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/isUndefined' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/object/copyAttributes' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/object/dictionaryFrom' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/object/hasKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/object/isObject' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/string/capitalize' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/string/isString' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/string/normalizeEventName' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/utils/string/stripSuperfluousWhitespace' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/vendor/react-dom/getEventCharCode' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/vendor/react-dom/reactsGetEventKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/vendor/react-dom/translateToKey' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/withHotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/withHotKeysIgnoreOverride' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/withIgnoreKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/es/withObserveKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/index.es' {
  declare module.exports: any;
}

declare module 'react-hotkeys/umd/react-hotkeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/umd/react-hotkeys.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hotkeys/cjs/configure.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/configure'>;
}
declare module 'react-hotkeys/cjs/const/AltedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/AltedKeysDictionary'>;
}
declare module 'react-hotkeys/cjs/const/AltShiftedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/AltShiftedKeysDictionary'>;
}
declare module 'react-hotkeys/cjs/const/EventResponse.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/EventResponse'>;
}
declare module 'react-hotkeys/cjs/const/KeyEventSequenceIndex.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/KeyEventSequenceIndex'>;
}
declare module 'react-hotkeys/cjs/const/KeyEventState.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/KeyEventState'>;
}
declare module 'react-hotkeys/cjs/const/KeyEventType.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/KeyEventType'>;
}
declare module 'react-hotkeys/cjs/const/KeyOSAndLayoutAliasesDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/KeyOSAndLayoutAliasesDictionary'>;
}
declare module 'react-hotkeys/cjs/const/KeyShorthandDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/KeyShorthandDictionary'>;
}
declare module 'react-hotkeys/cjs/const/KeysWithKeyUpHiddenByCmd.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/KeysWithKeyUpHiddenByCmd'>;
}
declare module 'react-hotkeys/cjs/const/ModifierFlagsDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/ModifierFlagsDictionary'>;
}
declare module 'react-hotkeys/cjs/const/MousetrapToReactKeyNamesDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/MousetrapToReactKeyNamesDictionary'>;
}
declare module 'react-hotkeys/cjs/const/NonPrintableKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/NonPrintableKeysDictionary'>;
}
declare module 'react-hotkeys/cjs/const/reverse-dictionaries/UnaltedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/reverse-dictionaries/UnaltedKeysDictionary'>;
}
declare module 'react-hotkeys/cjs/const/reverse-dictionaries/UnaltShiftedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/reverse-dictionaries/UnaltShiftedKeysDictionary'>;
}
declare module 'react-hotkeys/cjs/const/reverse-dictionaries/UnshiftedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/reverse-dictionaries/UnshiftedKeysDictionary'>;
}
declare module 'react-hotkeys/cjs/const/ShiftedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/const/ShiftedKeysDictionary'>;
}
declare module 'react-hotkeys/cjs/deprecatedWithHotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/deprecatedWithHotKeys'>;
}
declare module 'react-hotkeys/cjs/getApplicationKeyMap.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/getApplicationKeyMap'>;
}
declare module 'react-hotkeys/cjs/GlobalHotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/GlobalHotKeys'>;
}
declare module 'react-hotkeys/cjs/helpers/logging/describeKeyEvent.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/logging/describeKeyEvent'>;
}
declare module 'react-hotkeys/cjs/helpers/logging/describeKeyEventType.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/logging/describeKeyEventType'>;
}
declare module 'react-hotkeys/cjs/helpers/logging/printComponent.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/logging/printComponent'>;
}
declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/isCmdKey.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/parsing-key-maps/isCmdKey'>;
}
declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/isCustomKeyName.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/parsing-key-maps/isCustomKeyName'>;
}
declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/isNonPrintableKeyName.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/parsing-key-maps/isNonPrintableKeyName'>;
}
declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/isValidKey.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/parsing-key-maps/isValidKey'>;
}
declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/standardizeKeyName.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/parsing-key-maps/standardizeKeyName'>;
}
declare module 'react-hotkeys/cjs/helpers/parsing-key-maps/stateFromEvent.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/parsing-key-maps/stateFromEvent'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/applicableAliasFunctions.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/applicableAliasFunctions'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/getKeyName.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/getKeyName'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/hasKeyPressEvent.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/hasKeyPressEvent'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/isFromFocusOnlyComponent.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/isFromFocusOnlyComponent'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/keyupIsHiddenByCmd.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/keyupIsHiddenByCmd'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveAltedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/resolveAltedAlias'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveAltShiftedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/resolveAltShiftedAlias'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveKeyAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/resolveKeyAlias'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveShiftedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/resolveShiftedAlias'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnaltedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnaltedAlias'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnaltShiftedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnaltShiftedAlias'>;
}
declare module 'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnshiftedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/helpers/resolving-handlers/resolveUnshiftedAlias'>;
}
declare module 'react-hotkeys/cjs/HotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/HotKeys'>;
}
declare module 'react-hotkeys/cjs/IgnoreKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/IgnoreKeys'>;
}
declare module 'react-hotkeys/cjs/index' {
  declare module.exports: $Exports<'react-hotkeys/cjs'>;
}
declare module 'react-hotkeys/cjs/index.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs'>;
}
declare module 'react-hotkeys/cjs/lib/config/Configuration.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/config/Configuration'>;
}
declare module 'react-hotkeys/cjs/lib/definitions/ComponentOptionsList.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/definitions/ComponentOptionsList'>;
}
declare module 'react-hotkeys/cjs/lib/definitions/ComponentOptionsListIterator.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/definitions/ComponentOptionsListIterator'>;
}
declare module 'react-hotkeys/cjs/lib/definitions/ComponentTree.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/definitions/ComponentTree'>;
}
declare module 'react-hotkeys/cjs/lib/KeyEventManager.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/KeyEventManager'>;
}
declare module 'react-hotkeys/cjs/lib/listening/EventPropagator.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/listening/EventPropagator'>;
}
declare module 'react-hotkeys/cjs/lib/listening/KeyCombination.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/listening/KeyCombination'>;
}
declare module 'react-hotkeys/cjs/lib/listening/KeyEventCounter.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/listening/KeyEventCounter'>;
}
declare module 'react-hotkeys/cjs/lib/listening/KeyHistory.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/listening/KeyHistory'>;
}
declare module 'react-hotkeys/cjs/lib/logging/Logger.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/logging/Logger'>;
}
declare module 'react-hotkeys/cjs/lib/matching/ActionResolver.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/matching/ActionResolver'>;
}
declare module 'react-hotkeys/cjs/lib/matching/KeyCombinationMatcher.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/matching/KeyCombinationMatcher'>;
}
declare module 'react-hotkeys/cjs/lib/matching/KeyHistoryMatcher.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/matching/KeyHistoryMatcher'>;
}
declare module 'react-hotkeys/cjs/lib/shared/KeyCombinationSerializer.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/shared/KeyCombinationSerializer'>;
}
declare module 'react-hotkeys/cjs/lib/shared/KeyEventStateArrayManager.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/shared/KeyEventStateArrayManager'>;
}
declare module 'react-hotkeys/cjs/lib/shared/KeySequenceParser.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/shared/KeySequenceParser'>;
}
declare module 'react-hotkeys/cjs/lib/shared/Registry.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/shared/Registry'>;
}
declare module 'react-hotkeys/cjs/lib/strategies/AbstractKeyEventStrategy.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/strategies/AbstractKeyEventStrategy'>;
}
declare module 'react-hotkeys/cjs/lib/strategies/FocusOnlyKeyEventStrategy.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/strategies/FocusOnlyKeyEventStrategy'>;
}
declare module 'react-hotkeys/cjs/lib/strategies/GlobalKeyEventStrategy.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/lib/strategies/GlobalKeyEventStrategy'>;
}
declare module 'react-hotkeys/cjs/ObserveKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/ObserveKeys'>;
}
declare module 'react-hotkeys/cjs/react-hotkeys.production.min.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/react-hotkeys.production.min'>;
}
declare module 'react-hotkeys/cjs/recordKeyCombination.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/recordKeyCombination'>;
}
declare module 'react-hotkeys/cjs/utils/array/arrayFrom.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/array/arrayFrom'>;
}
declare module 'react-hotkeys/cjs/utils/array/indexFromEnd.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/array/indexFromEnd'>;
}
declare module 'react-hotkeys/cjs/utils/array/removeAtIndex.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/array/removeAtIndex'>;
}
declare module 'react-hotkeys/cjs/utils/backwardsCompatibleContext.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/backwardsCompatibleContext'>;
}
declare module 'react-hotkeys/cjs/utils/collection/contains.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/collection/contains'>;
}
declare module 'react-hotkeys/cjs/utils/collection/isEmpty.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/collection/isEmpty'>;
}
declare module 'react-hotkeys/cjs/utils/collection/size.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/collection/size'>;
}
declare module 'react-hotkeys/cjs/utils/collection/without.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/collection/without'>;
}
declare module 'react-hotkeys/cjs/utils/invertArrayDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/invertArrayDictionary'>;
}
declare module 'react-hotkeys/cjs/utils/isUndefined.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/isUndefined'>;
}
declare module 'react-hotkeys/cjs/utils/object/copyAttributes.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/object/copyAttributes'>;
}
declare module 'react-hotkeys/cjs/utils/object/dictionaryFrom.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/object/dictionaryFrom'>;
}
declare module 'react-hotkeys/cjs/utils/object/hasKey.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/object/hasKey'>;
}
declare module 'react-hotkeys/cjs/utils/object/isObject.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/object/isObject'>;
}
declare module 'react-hotkeys/cjs/utils/string/capitalize.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/string/capitalize'>;
}
declare module 'react-hotkeys/cjs/utils/string/isString.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/string/isString'>;
}
declare module 'react-hotkeys/cjs/utils/string/normalizeEventName.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/string/normalizeEventName'>;
}
declare module 'react-hotkeys/cjs/utils/string/stripSuperfluousWhitespace.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/utils/string/stripSuperfluousWhitespace'>;
}
declare module 'react-hotkeys/cjs/vendor/react-dom/getEventCharCode.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/vendor/react-dom/getEventCharCode'>;
}
declare module 'react-hotkeys/cjs/vendor/react-dom/reactsGetEventKey.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/vendor/react-dom/reactsGetEventKey'>;
}
declare module 'react-hotkeys/cjs/vendor/react-dom/translateToKey.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/vendor/react-dom/translateToKey'>;
}
declare module 'react-hotkeys/cjs/withHotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/withHotKeys'>;
}
declare module 'react-hotkeys/cjs/withHotKeysIgnoreOverride.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/withHotKeysIgnoreOverride'>;
}
declare module 'react-hotkeys/cjs/withIgnoreKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/withIgnoreKeys'>;
}
declare module 'react-hotkeys/cjs/withObserveKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/cjs/withObserveKeys'>;
}
declare module 'react-hotkeys/es/configure.js' {
  declare module.exports: $Exports<'react-hotkeys/es/configure'>;
}
declare module 'react-hotkeys/es/const/AltedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/AltedKeysDictionary'>;
}
declare module 'react-hotkeys/es/const/AltShiftedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/AltShiftedKeysDictionary'>;
}
declare module 'react-hotkeys/es/const/EventResponse.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/EventResponse'>;
}
declare module 'react-hotkeys/es/const/KeyEventSequenceIndex.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/KeyEventSequenceIndex'>;
}
declare module 'react-hotkeys/es/const/KeyEventState.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/KeyEventState'>;
}
declare module 'react-hotkeys/es/const/KeyEventType.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/KeyEventType'>;
}
declare module 'react-hotkeys/es/const/KeyOSAndLayoutAliasesDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/KeyOSAndLayoutAliasesDictionary'>;
}
declare module 'react-hotkeys/es/const/KeyShorthandDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/KeyShorthandDictionary'>;
}
declare module 'react-hotkeys/es/const/KeysWithKeyUpHiddenByCmd.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/KeysWithKeyUpHiddenByCmd'>;
}
declare module 'react-hotkeys/es/const/ModifierFlagsDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/ModifierFlagsDictionary'>;
}
declare module 'react-hotkeys/es/const/MousetrapToReactKeyNamesDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/MousetrapToReactKeyNamesDictionary'>;
}
declare module 'react-hotkeys/es/const/NonPrintableKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/NonPrintableKeysDictionary'>;
}
declare module 'react-hotkeys/es/const/reverse-dictionaries/UnaltedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/reverse-dictionaries/UnaltedKeysDictionary'>;
}
declare module 'react-hotkeys/es/const/reverse-dictionaries/UnaltShiftedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/reverse-dictionaries/UnaltShiftedKeysDictionary'>;
}
declare module 'react-hotkeys/es/const/reverse-dictionaries/UnshiftedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/reverse-dictionaries/UnshiftedKeysDictionary'>;
}
declare module 'react-hotkeys/es/const/ShiftedKeysDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/const/ShiftedKeysDictionary'>;
}
declare module 'react-hotkeys/es/deprecatedWithHotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/deprecatedWithHotKeys'>;
}
declare module 'react-hotkeys/es/getApplicationKeyMap.js' {
  declare module.exports: $Exports<'react-hotkeys/es/getApplicationKeyMap'>;
}
declare module 'react-hotkeys/es/GlobalHotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/GlobalHotKeys'>;
}
declare module 'react-hotkeys/es/helpers/logging/describeKeyEvent.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/logging/describeKeyEvent'>;
}
declare module 'react-hotkeys/es/helpers/logging/describeKeyEventType.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/logging/describeKeyEventType'>;
}
declare module 'react-hotkeys/es/helpers/logging/printComponent.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/logging/printComponent'>;
}
declare module 'react-hotkeys/es/helpers/parsing-key-maps/isCmdKey.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/parsing-key-maps/isCmdKey'>;
}
declare module 'react-hotkeys/es/helpers/parsing-key-maps/isCustomKeyName.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/parsing-key-maps/isCustomKeyName'>;
}
declare module 'react-hotkeys/es/helpers/parsing-key-maps/isNonPrintableKeyName.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/parsing-key-maps/isNonPrintableKeyName'>;
}
declare module 'react-hotkeys/es/helpers/parsing-key-maps/isValidKey.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/parsing-key-maps/isValidKey'>;
}
declare module 'react-hotkeys/es/helpers/parsing-key-maps/standardizeKeyName.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/parsing-key-maps/standardizeKeyName'>;
}
declare module 'react-hotkeys/es/helpers/parsing-key-maps/stateFromEvent.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/parsing-key-maps/stateFromEvent'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/applicableAliasFunctions.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/applicableAliasFunctions'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/getKeyName.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/getKeyName'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/hasKeyPressEvent.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/hasKeyPressEvent'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/isFromFocusOnlyComponent.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/isFromFocusOnlyComponent'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/keyupIsHiddenByCmd.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/keyupIsHiddenByCmd'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveAltedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/resolveAltedAlias'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveAltShiftedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/resolveAltShiftedAlias'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveKeyAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/resolveKeyAlias'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveShiftedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/resolveShiftedAlias'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveUnaltedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/resolveUnaltedAlias'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveUnaltShiftedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/resolveUnaltShiftedAlias'>;
}
declare module 'react-hotkeys/es/helpers/resolving-handlers/resolveUnshiftedAlias.js' {
  declare module.exports: $Exports<'react-hotkeys/es/helpers/resolving-handlers/resolveUnshiftedAlias'>;
}
declare module 'react-hotkeys/es/HotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/HotKeys'>;
}
declare module 'react-hotkeys/es/IgnoreKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/IgnoreKeys'>;
}
declare module 'react-hotkeys/es/index' {
  declare module.exports: $Exports<'react-hotkeys/es'>;
}
declare module 'react-hotkeys/es/index.js' {
  declare module.exports: $Exports<'react-hotkeys/es'>;
}
declare module 'react-hotkeys/es/lib/config/Configuration.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/config/Configuration'>;
}
declare module 'react-hotkeys/es/lib/definitions/ComponentOptionsList.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/definitions/ComponentOptionsList'>;
}
declare module 'react-hotkeys/es/lib/definitions/ComponentOptionsListIterator.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/definitions/ComponentOptionsListIterator'>;
}
declare module 'react-hotkeys/es/lib/definitions/ComponentTree.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/definitions/ComponentTree'>;
}
declare module 'react-hotkeys/es/lib/KeyEventManager.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/KeyEventManager'>;
}
declare module 'react-hotkeys/es/lib/listening/EventPropagator.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/listening/EventPropagator'>;
}
declare module 'react-hotkeys/es/lib/listening/KeyCombination.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/listening/KeyCombination'>;
}
declare module 'react-hotkeys/es/lib/listening/KeyEventCounter.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/listening/KeyEventCounter'>;
}
declare module 'react-hotkeys/es/lib/listening/KeyHistory.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/listening/KeyHistory'>;
}
declare module 'react-hotkeys/es/lib/logging/Logger.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/logging/Logger'>;
}
declare module 'react-hotkeys/es/lib/matching/ActionResolver.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/matching/ActionResolver'>;
}
declare module 'react-hotkeys/es/lib/matching/KeyCombinationMatcher.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/matching/KeyCombinationMatcher'>;
}
declare module 'react-hotkeys/es/lib/matching/KeyHistoryMatcher.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/matching/KeyHistoryMatcher'>;
}
declare module 'react-hotkeys/es/lib/shared/KeyCombinationSerializer.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/shared/KeyCombinationSerializer'>;
}
declare module 'react-hotkeys/es/lib/shared/KeyEventStateArrayManager.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/shared/KeyEventStateArrayManager'>;
}
declare module 'react-hotkeys/es/lib/shared/KeySequenceParser.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/shared/KeySequenceParser'>;
}
declare module 'react-hotkeys/es/lib/shared/Registry.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/shared/Registry'>;
}
declare module 'react-hotkeys/es/lib/strategies/AbstractKeyEventStrategy.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/strategies/AbstractKeyEventStrategy'>;
}
declare module 'react-hotkeys/es/lib/strategies/FocusOnlyKeyEventStrategy.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/strategies/FocusOnlyKeyEventStrategy'>;
}
declare module 'react-hotkeys/es/lib/strategies/GlobalKeyEventStrategy.js' {
  declare module.exports: $Exports<'react-hotkeys/es/lib/strategies/GlobalKeyEventStrategy'>;
}
declare module 'react-hotkeys/es/ObserveKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/ObserveKeys'>;
}
declare module 'react-hotkeys/es/react-hotkeys.production.min.js' {
  declare module.exports: $Exports<'react-hotkeys/es/react-hotkeys.production.min'>;
}
declare module 'react-hotkeys/es/recordKeyCombination.js' {
  declare module.exports: $Exports<'react-hotkeys/es/recordKeyCombination'>;
}
declare module 'react-hotkeys/es/utils/array/arrayFrom.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/array/arrayFrom'>;
}
declare module 'react-hotkeys/es/utils/array/indexFromEnd.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/array/indexFromEnd'>;
}
declare module 'react-hotkeys/es/utils/array/removeAtIndex.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/array/removeAtIndex'>;
}
declare module 'react-hotkeys/es/utils/backwardsCompatibleContext.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/backwardsCompatibleContext'>;
}
declare module 'react-hotkeys/es/utils/collection/contains.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/collection/contains'>;
}
declare module 'react-hotkeys/es/utils/collection/isEmpty.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/collection/isEmpty'>;
}
declare module 'react-hotkeys/es/utils/collection/size.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/collection/size'>;
}
declare module 'react-hotkeys/es/utils/collection/without.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/collection/without'>;
}
declare module 'react-hotkeys/es/utils/invertArrayDictionary.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/invertArrayDictionary'>;
}
declare module 'react-hotkeys/es/utils/isUndefined.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/isUndefined'>;
}
declare module 'react-hotkeys/es/utils/object/copyAttributes.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/object/copyAttributes'>;
}
declare module 'react-hotkeys/es/utils/object/dictionaryFrom.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/object/dictionaryFrom'>;
}
declare module 'react-hotkeys/es/utils/object/hasKey.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/object/hasKey'>;
}
declare module 'react-hotkeys/es/utils/object/isObject.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/object/isObject'>;
}
declare module 'react-hotkeys/es/utils/string/capitalize.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/string/capitalize'>;
}
declare module 'react-hotkeys/es/utils/string/isString.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/string/isString'>;
}
declare module 'react-hotkeys/es/utils/string/normalizeEventName.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/string/normalizeEventName'>;
}
declare module 'react-hotkeys/es/utils/string/stripSuperfluousWhitespace.js' {
  declare module.exports: $Exports<'react-hotkeys/es/utils/string/stripSuperfluousWhitespace'>;
}
declare module 'react-hotkeys/es/vendor/react-dom/getEventCharCode.js' {
  declare module.exports: $Exports<'react-hotkeys/es/vendor/react-dom/getEventCharCode'>;
}
declare module 'react-hotkeys/es/vendor/react-dom/reactsGetEventKey.js' {
  declare module.exports: $Exports<'react-hotkeys/es/vendor/react-dom/reactsGetEventKey'>;
}
declare module 'react-hotkeys/es/vendor/react-dom/translateToKey.js' {
  declare module.exports: $Exports<'react-hotkeys/es/vendor/react-dom/translateToKey'>;
}
declare module 'react-hotkeys/es/withHotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/withHotKeys'>;
}
declare module 'react-hotkeys/es/withHotKeysIgnoreOverride.js' {
  declare module.exports: $Exports<'react-hotkeys/es/withHotKeysIgnoreOverride'>;
}
declare module 'react-hotkeys/es/withIgnoreKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/withIgnoreKeys'>;
}
declare module 'react-hotkeys/es/withObserveKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/es/withObserveKeys'>;
}
declare module 'react-hotkeys/index.es.js' {
  declare module.exports: $Exports<'react-hotkeys/index.es'>;
}
declare module 'react-hotkeys/index' {
  declare module.exports: $Exports<'react-hotkeys'>;
}
declare module 'react-hotkeys/index.js' {
  declare module.exports: $Exports<'react-hotkeys'>;
}
declare module 'react-hotkeys/umd/react-hotkeys.js' {
  declare module.exports: $Exports<'react-hotkeys/umd/react-hotkeys'>;
}
declare module 'react-hotkeys/umd/react-hotkeys.min.js' {
  declare module.exports: $Exports<'react-hotkeys/umd/react-hotkeys.min'>;
}
