// flow-typed signature: c3fc8562949b283c3446e92f8d6db4e2
// flow-typed version: <<STUB>>/react-composition-input_v^1.1.1/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-composition-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-composition-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-composition-input/lib' {
  declare module.exports: any;
}

declare module 'react-composition-input/lib/inputfield' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-composition-input/lib/index' {
  declare module.exports: $Exports<'react-composition-input/lib'>;
}
declare module 'react-composition-input/lib/index.js' {
  declare module.exports: $Exports<'react-composition-input/lib'>;
}
declare module 'react-composition-input/lib/inputfield.js' {
  declare module.exports: $Exports<'react-composition-input/lib/inputfield'>;
}
