// flow-typed signature: 754c7b3f862d5fa29064175b8845dcd5
// flow-typed version: <<STUB>>/react-values_v^0.3.3/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-values' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-values/dist/react-values' {
  declare module.exports: any;
}

declare module 'react-values/dist/react-values.min' {
  declare module.exports: any;
}

declare module 'react-values/lib/react-values.es' {
  declare module.exports: any;
}

declare module 'react-values/lib/react-values' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-values/dist/react-values.js' {
  declare module.exports: $Exports<'react-values/dist/react-values'>;
}
declare module 'react-values/dist/react-values.min.js' {
  declare module.exports: $Exports<'react-values/dist/react-values.min'>;
}
declare module 'react-values/lib/react-values.es.js' {
  declare module.exports: $Exports<'react-values/lib/react-values.es'>;
}
declare module 'react-values/lib/react-values.js' {
  declare module.exports: $Exports<'react-values/lib/react-values'>;
}
