// flow-typed signature: 1a23536f90727ab3224026279e763455
// flow-typed version: <<STUB>>/tippy.js_v^5.0.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tippy.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tippy.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tippy.js/dist/tippy-bundle.cjs' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy-bundle.esm' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy-bundle.iife' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy-bundle.iife.min' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy.chunk.cjs' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy.chunk.esm' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy.cjs' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy.esm' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy.iife' {
  declare module.exports: any;
}

declare module 'tippy.js/dist/tippy.iife.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tippy.js/dist/tippy-bundle.cjs.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy-bundle.cjs'>;
}
declare module 'tippy.js/dist/tippy-bundle.esm.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy-bundle.esm'>;
}
declare module 'tippy.js/dist/tippy-bundle.iife.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy-bundle.iife'>;
}
declare module 'tippy.js/dist/tippy-bundle.iife.min.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy-bundle.iife.min'>;
}
declare module 'tippy.js/dist/tippy.chunk.cjs.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy.chunk.cjs'>;
}
declare module 'tippy.js/dist/tippy.chunk.esm.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy.chunk.esm'>;
}
declare module 'tippy.js/dist/tippy.cjs.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy.cjs'>;
}
declare module 'tippy.js/dist/tippy.esm.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy.esm'>;
}
declare module 'tippy.js/dist/tippy.iife.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy.iife'>;
}
declare module 'tippy.js/dist/tippy.iife.min.js' {
  declare module.exports: $Exports<'tippy.js/dist/tippy.iife.min'>;
}
