// flow-typed signature: 0be6651a41780e18dba4e208c857d599
// flow-typed version: <<STUB>>/tippy.js_v4.3.5/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tippy.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tippy.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tippy.js/esm/index.all' {
  declare module.exports: any;
}

declare module 'tippy.js/esm/index.all.min' {
  declare module.exports: any;
}

declare module 'tippy.js/esm' {
  declare module.exports: any;
}

declare module 'tippy.js/esm/index.min' {
  declare module.exports: any;
}

declare module 'tippy.js/umd/index.all' {
  declare module.exports: any;
}

declare module 'tippy.js/umd/index.all.min' {
  declare module.exports: any;
}

declare module 'tippy.js/umd' {
  declare module.exports: any;
}

declare module 'tippy.js/umd/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tippy.js/esm/index.all.js' {
  declare module.exports: $Exports<'tippy.js/esm/index.all'>;
}
declare module 'tippy.js/esm/index.all.min.js' {
  declare module.exports: $Exports<'tippy.js/esm/index.all.min'>;
}
declare module 'tippy.js/esm/index' {
  declare module.exports: $Exports<'tippy.js/esm'>;
}
declare module 'tippy.js/esm/index.js' {
  declare module.exports: $Exports<'tippy.js/esm'>;
}
declare module 'tippy.js/esm/index.min.js' {
  declare module.exports: $Exports<'tippy.js/esm/index.min'>;
}
declare module 'tippy.js/umd/index.all.js' {
  declare module.exports: $Exports<'tippy.js/umd/index.all'>;
}
declare module 'tippy.js/umd/index.all.min.js' {
  declare module.exports: $Exports<'tippy.js/umd/index.all.min'>;
}
declare module 'tippy.js/umd/index' {
  declare module.exports: $Exports<'tippy.js/umd'>;
}
declare module 'tippy.js/umd/index.js' {
  declare module.exports: $Exports<'tippy.js/umd'>;
}
declare module 'tippy.js/umd/index.min.js' {
  declare module.exports: $Exports<'tippy.js/umd/index.min'>;
}
