// flow-typed signature: 86caa714368464d03ecc346eb5593dea
// flow-typed version: <<STUB>>/unstated-debug_v^0.4.0/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unstated-debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unstated-debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'unstated-debug/index' {
  declare module.exports: $Exports<'unstated-debug'>;
}
declare module 'unstated-debug/index.js' {
  declare module.exports: $Exports<'unstated-debug'>;
}
