// flow-typed signature: 14b28ec196822605c20594e31e2d9ed1
// flow-typed version: <<STUB>>/unstated-next_v^1.1.0/flow_v0.111.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unstated-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unstated-next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unstated-next/dist/unstated-next' {
  declare module.exports: any;
}

declare module 'unstated-next/dist/unstated-next.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unstated-next/dist/unstated-next.js' {
  declare module.exports: $Exports<'unstated-next/dist/unstated-next'>;
}
declare module 'unstated-next/dist/unstated-next.umd.js' {
  declare module.exports: $Exports<'unstated-next/dist/unstated-next.umd'>;
}
