// @flow
export const orderFieldKeys = [
  'order.PO',
  'order.PI',
  'order.date',
  'order.deliveryDate',
  'order.exporterName',
  'order.exporterCode',
  'order.currency',
  'order.incoterm',
  'order.deliveryPlace',
  'order.inCharge',
  'order.tags',
  'order.totalItemQuantity',
  'order.totalPrice',
  'order.totalVolume',
];
export const orderItemFieldKeys = [
  'orderItem.name',
  'orderItem.serial',
  'orderItem.exporterName',
  'orderItem.exporterCode',
  'orderItem.supplierName',
  'orderItem.supplierCode',
  'orderItem.unitPrice',
  'orderItem.unitPriceCurrency',
  'orderItem.quantity',
  'orderItem.totalPrice',
];
export const batchFieldKeys = [
  'batch.batchNo',
  'batch.quantity',
  'batch.newQuantity1',
  'batch.newQuantity2',
  'batch.newQuantity3',
  'batch.newQuantity4',
  'batch.newQuantity5',
  'batch.deliveredAt',
  'batch.desiredAt',
  'batch.expiredAt',
  'batch.producedAt',
  'batch.tags',
  'batch.totalPrice',
];
