// Components or Routes
import {
  // Components
  faFileEdit as ORDER,
  faBox as BATCH,
  faShip as SHIPMENT,
  faContainerStorage as CONTAINER,
  faCube as PRODUCT,
  faWarehouse as WAREHOUSE,
  faInventory as INVENTORY,
  faAddressBook as NETWORK,
  faHandshake as PARTNER,
  faUsers as STAFF,
  faCog as SETTINGS,
  faTag as TAG,
  faShoppingCart as ORDER_ITEM,
  faBell as NOTIFICATION,
  faAddressCard as PROFILE,
  faSignInAlt as LOGIN,
  faSignOutAlt as LOGOUT,
  faIndustryAlt as EXPORTER,
  faShippingFast as FORWARDER,
  faUser as USER,
  faUserCrown as MANAGER,
  faTape as PACKAGING,
  faBalanceScale as QUANTITY_ADJUSTMENTS,
  faRoute as TIMELINE,
  faBoxesAlt as CARGO,
  faRulerTriangle as SPECIFICATIONS,
  faCameraAlt as PHOTO,
  faFileAlt as DOCUMENT,
  faMap as RELATION_MAP,
  faMapPin as MILESTONE,
  faBook as LOGS,
  faCalculator as CALCULATOR,
  faGripVertical as DRAG_HANDLE,
  faEdit as METADATA,
  faFileSpreadsheet as TEMPLATE,
  faClipboardCheck as TASK,
  faTable as EDIT_TABLE,
  faTable as TABLE,
  faShieldAlt as SECURITY,
  faKey as PASSWORD,
  faRedo as FORGOT,
  faFileImport as IMPORT,
  faTh as SHEET,
  faThLarge as CARDS,
  faThList as PROJECT,
  // Common UI
  faFolderOpen as ACTIVE,
  faArchive as ARCHIVE,
  faTh as CARD,
  faSortAmountDown as SORT_DESC,
  faSortAmountUp as SORT_ASC,
  faFilter as FILTER,
  faSearch as SEARCH,
  faTimes as CLEAR,
  faTimesCircle as CANCEL,
  faTrashAlt as REMOVE,
  faClone as CLONE,
  faCheckCircle as CHECKED,
  faCheckSquare as CHECKED_SQUARE,
  faBan as DISABLED,
  faToggleOn as TOGGLE_ON,
  faToggleOff as TOGGLE_OFF,
  faPencil as EDIT,
  faCheck as CONFIRM,
  faMinus as MINUS,
  faPlus as ADD,
  faSync as SYNC,
  faExchange as EXCHANGE,
  faExpand as EXPAND,
  faCompress as COMPRESS,
  faArrowDown as ARROW_DOWN,
  faArrowRight as ARROW_RIGHT,
  faChevronDown as CHEVRON_DOWN,
  faChevronLeft as CHEVRON_LEFT,
  faChevronDoubleLeft as CHEVRON_DOUBLE_LEFT,
  faChevronDoubleUp as CHEVRON_DOUBLE_UP,
  faChevronDoubleRight as CHEVRON_DOUBLE_RIGHT,
  faChevronDoubleDown as CHEVRON_DOUBLE_DOWN,
  faExclamationTriangle as WARNING_TRIANGLE,
  faExclamationCircle as WARNING,
  faInfoCircle as INFO,
  faCommentAltLines as MEMO,
  faCommentAltPlus as MEMO_ADD,
  faDownload as DOWNLOAD,
  faCircle as CIRCLE,
  faEllipsisH as HORIZONTAL_ELLIPSIS,
  faLanguage as LANGUAGE,
  faPalette as COLOR,
  faFeatherAlt as EDITED,
  faPaperPlane as PAPER_PLANE,
  faExternalLink as EXTERNAL_LINK,
  faEye as VISIBLE,
  faEyeSlash as INVISIBLE,
  faRedo as RELOAD,
  faClock as CLOCK,
  faThList as TH_LIST,
  faSitemap as RELATED,
  faProjectDiagram as MAP,
  faForward as SKIPPED,
  faUndo as UNDO,
  faBringForward as BRING_FORWARD,
  // Shipment Timeline
  faBoxCheck as CARGO_READY,
  faAnchor as PORT,
  faPlane as PLANE,
  faQuestion as UNKNOWN,
  faLifeRing as TRANSIT,
  faClipboardList as CUSTOMS,
  faTruckLoading as DELIVERY_READY,
  faArrowToBottom as ARRIVAL,
  faArrowFromTop as DEPARTURE,
  faArrowToRight as ARRIVAL_HORIZONTAL,
  faArrowFromLeft as DEPARTURE_HORIZONTAL,
  // Document Types
  faFileExcel as EXCEL,
  faFileCsv as CSV,
  faFileImage as IMAGE,
  faFilePdf as PDF,
  faFilePowerpoint as POWER_POINT,
  faFileWord as WORD,
  faLink as BINDED,
  faUnlink as UNBINDED,
  faBezierCurve as SPLIT,
  faBezierCurve as ENTITY,
  faMagic as MAGIC,
  faCodeBranch as BRANCH,
  faStar as STAR,
  faStopwatch as STOPWATCH,
} from '@fortawesome/pro-solid-svg-icons';

import {
  // Components
  faIndustryAlt as IMPORTER,
  faIndustry as SUPPLIER,
  faWarehouse as WAREHOUSER,
  faCube as PRODUCT_PROVIDER,
  // Common UI
  faList as LIST,
  faCheckCircle as UNCHECKED,
  faEye as EYE,
  faCodeBranch as BRANCH_REGULAR,
  faSquare as SQUARE,
  faAngleRight as TARGET,
  faMagic as MAGIC_REGULAR,
  faFileAlt as DOCUMENT_REGULAR,
  faCheckCircle as CHECKED_REGULAR,
  faStar as STAR_REGULAR,
} from '@fortawesome/pro-regular-svg-icons';

import {
  // Common UI
  faAngleLeft as ANGLE_LEFT,
  faAngleRight as ANGLE_RIGHT,
  faBox as BATCH_LIGHT,
  faShip as SHIPMENT_LIGHT,
  faArchive as ARCHIVE_LIGHT,
} from '@fortawesome/pro-light-svg-icons';

export default {
  ORDER,
  TASK,
  BATCH,
  SHIPMENT,
  CONTAINER,
  PRODUCT,
  WAREHOUSE,
  INVENTORY,
  NETWORK,
  PARTNER,
  STAFF,
  SETTINGS,
  TAG,
  ORDER_ITEM,
  NOTIFICATION,
  PROFILE,
  LOGIN,
  LOGOUT,
  IMPORTER,
  EXPORTER,
  FORWARDER,
  SUPPLIER,
  USER,
  MANAGER,
  WAREHOUSER,
  CARGO,
  PACKAGING,
  QUANTITY_ADJUSTMENTS,
  PRODUCT_PROVIDER,
  SPECIFICATIONS,
  PHOTO,
  LOGS,
  CALCULATOR,
  DRAG_HANDLE,
  METADATA,
  TEMPLATE,
  STAR,
  STAR_REGULAR,
  STOPWATCH,
  EDIT_TABLE,
  SECURITY,
  PASSWORD,
  FORGOT,
  IMPORT,
  SHEET,
  TH_LIST,
  RELATION_MAP,
  MILESTONE,
  BINDED,
  UNBINDED,
  SPLIT,
  RELATED,
  SKIPPED,
  UNDO,
  BRING_FORWARD,
  CARDS,
  PROJECT,

  BRANCH,
  ACTIVE,
  ARCHIVE,
  CARD,
  TABLE,
  LIST,
  SORT_DESC,
  SORT_ASC,
  FILTER,
  SEARCH,
  CLEAR,
  CANCEL,
  REMOVE,
  CLONE,
  CHECKED,
  CHECKED_SQUARE,
  UNCHECKED,
  DISABLED,
  EDIT,
  CONFIRM,
  MINUS,
  ADD,
  EYE,
  ARROW_DOWN,
  ARROW_RIGHT,
  WARNING_TRIANGLE,
  WARNING,
  CHEVRON_DOWN,
  CHEVRON_LEFT,
  ANGLE_LEFT,
  ANGLE_RIGHT,
  CHEVRON_DOUBLE_LEFT,
  CHEVRON_DOUBLE_UP,
  CHEVRON_DOUBLE_RIGHT,
  CHEVRON_DOUBLE_DOWN,
  DOCUMENT,
  TOGGLE_ON,
  TOGGLE_OFF,
  INFO,
  MEMO,
  MEMO_ADD,
  DOWNLOAD,
  CIRCLE,
  SYNC,
  EXPAND,
  COMPRESS,
  HORIZONTAL_ELLIPSIS,
  EXCHANGE,
  LANGUAGE,
  COLOR,
  EDITED,
  PAPER_PLANE,
  EXTERNAL_LINK,
  VISIBLE,
  INVISIBLE,
  RELOAD,
  CLOCK,
  MAP,

  TIMELINE,
  CARGO_READY,
  PORT,
  PLANE,
  UNKNOWN,
  TRANSIT,
  CUSTOMS,
  DELIVERY_READY,
  ARRIVAL,
  DEPARTURE,
  ARRIVAL_HORIZONTAL,
  DEPARTURE_HORIZONTAL,

  EXCEL,
  CSV,
  IMAGE,
  PDF,
  POWER_POINT,
  WORD,
  SQUARE,
  TARGET,
  ENTITY,
  MAGIC,
  BRANCH_REGULAR,
  MAGIC_REGULAR,
  DOCUMENT_REGULAR,
  CHECKED_REGULAR,
  BATCH_LIGHT,
  SHIPMENT_LIGHT,
  ARCHIVE_LIGHT,
};
