// Components or Routes
import {
  // Components
  faFileEdit as ORDER,
  faBox as BATCH,
  faShip as SHIPMENT,
  faCube as PRODUCT,
  faWarehouse as WAREHOUSE,
  faInventory as INVENTORY,
  faAddressBook as NETWORK,
  faHandshake as PARTNER,
  faUsers as STAFF,
  faCog as SETTINGS,
  faTag as TAG,
  faShoppingCart as ORDER_ITEM,
  faBell as NOTIFICATION,
  faAddressCard as PROFILE,
  faSignInAlt as LOGIN,
  faSignOutAlt as LOGOUT,
  faIndustryAlt as EXPORTER,
  faShippingFast as FORWARDER,
  faUser as USER,
  faUserCrown as MANAGER,
  faTape as PACKAGING,
  faBalanceScale as QUANTITY_ADJUSTMENTS,
  faRoute as TIMELINE,
  faBoxesAlt as CARGO,
  faRulerTriangle as SPECIFICATIONS,
  faCameraAlt as PHOTO,
  faFileAlt as DOCUMENT,
  faMap as RELATION_MAP,
  faBook as LOGS,
  faCalculator as CALCULATOR,
  faGripVertical as DRAG_HANDLE,
  // Common UI
  faFolderOpen as ACTIVE,
  faArchive as ARCHIVE,
  faTh as CARD,
  faSortAmountDown as SORT_DESC,
  faSortAmountUp as SORT_ASC,
  faFilter as FILTER,
  faSearch as SEARCH,
  faTimes as CLEAR,
  faTimesCircle as CANCEL,
  faTrashAlt as REMOVE,
  faClone as CLONE,
  faCheckCircle as CHECKED,
  faBan as DISABLED,
  faToggleOn as TOGGLE_ON,
  faToggleOff as TOGGLE_OFF,
  faPencil as EDIT,
  faCheck as CONFIRM,
  faMinus as MINUS,
  faPlus as ADD,
  faSync as SYNC,
  faExchange as EXCHANGE,
  faExpand as EXPAND,
  faCompress as COMPRESS,
  faArrowDown as ARROW_DOWN,
  faChevronDown as CHEVRON_DOWN,
  faChevronDoubleLeft as CHEVRON_DOUBLE_LEFT,
  faChevronDoubleRight as CHEVRON_DOUBLE_RIGHT,
  faExclamationCircle as WARNING,
  faInfoCircle as INFO,
  faCommentAltLines as MEMO,
  faCommentAltPlus as MEMO_ADD,
  faDownload as DOWNLOAD,
  faCircle as CIRCLE,
  faEllipsisH as HORIZONTAL_ELLIPSIS,
  faLanguage as LANGUAGE,
  faPalette as COLOR,
  faFeatherAlt as EDITED,
  faPaperPlane as PAPER_PLANE,
  faExternalLink as EXTERNAL_LINK,
  // Shipment Timeline
  faBoxCheck as CARGO_READY,
  faAnchor as PORT,
  faPlane as PLANE,
  faQuestion as UNKNOWN,
  faLifeRing as TRANSIT,
  faClipboardList as CUSTOMS,
  faTruckLoading as DELIVERY_READY,
  faArrowToBottom as ARRIVAL,
  faArrowFromTop as DEPARTURE,
  faArrowToRight as ARRIVAL_HORIZONTAL,
  faArrowFromLeft as DEPARTURE_HORIZONTAL,
  // Document Types
  faFileExcel as EXCEL,
  faFileImage as IMAGE,
  faFilePdf as PDF,
  faFilePowerpoint as POWER_POINT,
  faFileWord as WORD,
  faClipboardCheck as ORDER_SELECT,
  faLink as CONNECT,
  faBezierCurve as SPLIT,
  faBezierCurve as ENTITY,
  faMagic as MAGIC,
  faCodeBranch as BRANCH,
} from '@fortawesome/pro-solid-svg-icons';

import {
  // Components
  faIndustryAlt as IMPORTER,
  faIndustry as SUPPLIER,
  faWarehouse as WAREHOUSING,
  faCube as PROVIDER,
  // Common UI
  faThList as TABLE,
  faList as LIST,
  faCheckCircle as UNCHECKED,
  faEye as EYE,
  faCodeBranch as BRANCH_REGULAR,
  faSquare as SQUARE,
  faAngleRight as TARGET,
  faMagic as MAGIC_REGULAR,
  faFileAlt as DOCUMENT_REGULAR,
  faCheckCircle as CHECKED_REGULAR,
} from '@fortawesome/pro-regular-svg-icons';

import {
  // Common UI
  faAngleLeft as ANGLE_LEFT,
  faAngleRight as ANGLE_RIGHT,
} from '@fortawesome/pro-light-svg-icons';

export default {
  ORDER,
  ORDER_SELECT,
  BATCH,
  SHIPMENT,
  PRODUCT,
  WAREHOUSE,
  INVENTORY,
  NETWORK,
  PARTNER,
  STAFF,
  SETTINGS,
  TAG,
  ORDER_ITEM,
  NOTIFICATION,
  PROFILE,
  LOGIN,
  LOGOUT,
  IMPORTER,
  EXPORTER,
  FORWARDER,
  SUPPLIER,
  USER,
  MANAGER,
  WAREHOUSING,
  CARGO,
  PACKAGING,
  QUANTITY_ADJUSTMENTS,
  PROVIDER,
  SPECIFICATIONS,
  PHOTO,
  LOGS,
  CALCULATOR,
  DRAG_HANDLE,

  RELATION_MAP,
  CONNECT,
  SPLIT,

  BRANCH,
  ACTIVE,
  ARCHIVE,
  CARD,
  TABLE,
  LIST,
  SORT_DESC,
  SORT_ASC,
  FILTER,
  SEARCH,
  CLEAR,
  CANCEL,
  REMOVE,
  CLONE,
  CHECKED,
  UNCHECKED,
  DISABLED,
  EDIT,
  CONFIRM,
  MINUS,
  ADD,
  EYE,
  ARROW_DOWN,
  WARNING,
  CHEVRON_DOWN,
  ANGLE_LEFT,
  ANGLE_RIGHT,
  CHEVRON_DOUBLE_LEFT,
  CHEVRON_DOUBLE_RIGHT,
  DOCUMENT,
  TOGGLE_ON,
  TOGGLE_OFF,
  INFO,
  MEMO,
  MEMO_ADD,
  DOWNLOAD,
  CIRCLE,
  SYNC,
  EXPAND,
  COMPRESS,
  HORIZONTAL_ELLIPSIS,
  EXCHANGE,
  LANGUAGE,
  COLOR,
  EDITED,
  PAPER_PLANE,
  EXTERNAL_LINK,

  TIMELINE,
  CARGO_READY,
  PORT,
  PLANE,
  UNKNOWN,
  TRANSIT,
  CUSTOMS,
  DELIVERY_READY,
  ARRIVAL,
  DEPARTURE,
  ARRIVAL_HORIZONTAL,
  DEPARTURE_HORIZONTAL,

  EXCEL,
  IMAGE,
  PDF,
  POWER_POINT,
  WORD,
  SQUARE,
  TARGET,
  ENTITY,
  MAGIC,
  BRANCH_REGULAR,
  MAGIC_REGULAR,
  DOCUMENT_REGULAR,
  CHECKED_REGULAR,
};
