// Components or Routes
import {
  // Components
  faFileEdit as ORDER,
  faBox as BATCH,
  faShip as SHIPMENT,
  faCube as PRODUCT,
  faWarehouseAlt as WAREHOUSE,
  faInventory as INVENTORY,
  faAddressBook as NETWORK,
  faHandshake as PARTNER,
  faUsers as STAFF,
  faCog as SETTINGS,
  faTags as TAGS,
  faShoppingCart as ORDER_ITEM,
  faBell as NOTIFICATION,
  faAddressCard as PROFILE,
  faSignInAlt as LOGIN,
  faSignOutAlt as LOGOUT,
  faIndustryAlt as EXPORTER,
  faShippingFast as FORWARDER,
  faTape as PACKAGING,
  faBalanceScale as QUANTITY_ADJUSTMENTS,
  faRoute as TIMELINE,
  faBoxesAlt as CARGO,
  faIndustry as PROVIDER,
  faRulerTriangle as SPECIFICATIONS,
  faFileAlt as DOCUMENT,
  faMap as RELATION_MAP,
  // Common UI
  faFolderOpen as ACTIVE,
  faArchive as ARCHIVE,
  faTh as CARD,
  faSortAmountDown as SORT_DESC,
  faSortAmountUp as SORT_ASC,
  faFilter as FILTER,
  faSearch as SEARCH,
  faTimes as CLEAR,
  faTimesCircle as CANCEL,
  faToggleOn as TOGGLE_ON,
  faToggleOff as TOGGLE_OFF,
  faTrashAlt as REMOVE,
  faClone as CLONE,
  faCheckCircle as CHECKED,
  faBan as DISABLED,
  faPencil as EDIT,
  faCheck as CONFIRM,
  faMinus as MINUS,
  faPlus as ADD,
  faSync as SYNC,
  faExchange as EXCHANGE,
  faExpand as EXPAND,
  faCompress as COMPRESS,
  faArrowDown as ARROW_DOWN,
  faChevronDown as CHEVRON_DOWN,
  faChevronDoubleLeft as CHEVRON_DOUBLE_LEFT,
  faChevronDoubleRight as CHEVRON_DOUBLE_RIGHT,
  faExclamationCircle as WARNING,
  faInfoCircle as INFO,
  faCommentAltLines as MEMO,
  faCommentAltPlus as MEMO_ADD,
  faDownload as DOWNLOAD,
  faCircle as CIRCLE,
  faEllipsisH as HORIZONTAL_ELLIPSIS,
  faLanguage as LANGUAGE,
  // Shipment Timeline
  faBoxCheck as CARGO_READY,
  faAnchor as PORT,
  faPlane as PLANE,
  faQuestion as UNKNOWN,
  faLifeRing as TRANSIT,
  faClipboardList as CUSTOMS,
  faTruckLoading as DELIVERY_READY,
  faArrowToBottom as ARRIVAL,
  faArrowFromTop as DEPARTURE,
  // Document Types
  faFileExcel as EXCEL,
  faFileImage as IMAGE,
  faFilePdf as PDF,
  faFilePowerpoint as POWER_POINT,
  faFileWord as WORD,
} from '@fortawesome/pro-solid-svg-icons';

import {
  // Components
  faIndustry as SUPPLIER,
  // Common UI
  faThList as TABLE,
  faList as LIST,
  faCheckCircle as UNCHECKED,
  faEye as EYE,
} from '@fortawesome/pro-regular-svg-icons';

export default {
  ORDER,
  BATCH,
  SHIPMENT,
  PRODUCT,
  WAREHOUSE,
  INVENTORY,
  NETWORK,
  PARTNER,
  STAFF,
  SETTINGS,
  TAGS,
  ORDER_ITEM,
  NOTIFICATION,
  PROFILE,
  LOGIN,
  LOGOUT,
  EXPORTER,
  FORWARDER,
  SUPPLIER,
  CARGO,
  PACKAGING,
  QUANTITY_ADJUSTMENTS,
  PROVIDER,
  SPECIFICATIONS,

  RELATION_MAP,

  ACTIVE,
  ARCHIVE,
  CARD,
  TABLE,
  LIST,
  SORT_DESC,
  SORT_ASC,
  FILTER,
  SEARCH,
  CLEAR,
  CANCEL,
  REMOVE,
  CLONE,
  CHECKED,
  UNCHECKED,
  DISABLED,
  EDIT,
  CONFIRM,
  MINUS,
  ADD,
  EYE,
  ARROW_DOWN,
  WARNING,
  CHEVRON_DOWN,
  CHEVRON_DOUBLE_LEFT,
  CHEVRON_DOUBLE_RIGHT,
  DOCUMENT,
  TOGGLE_ON,
  TOGGLE_OFF,
  INFO,
  MEMO,
  MEMO_ADD,
  DOWNLOAD,
  CIRCLE,
  SYNC,
  EXPAND,
  COMPRESS,
  HORIZONTAL_ELLIPSIS,
  EXCHANGE,
  LANGUAGE,

  TIMELINE,
  CARGO_READY,
  PORT,
  PLANE,
  UNKNOWN,
  TRANSIT,
  CUSTOMS,
  DELIVERY_READY,
  ARRIVAL,
  DEPARTURE,

  EXCEL,
  IMAGE,
  PDF,
  POWER_POINT,
  WORD,
};
