// flow-typed signature: b399309fff5cfe17916012fe11febacf
// flow-typed version: <<STUB>>/@tippy.js/react_v2.2.3/flow_v0.110.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tippy.js/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tippy.js/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tippy.js/react/esm' {
  declare module.exports: any;
}

declare module '@tippy.js/react/esm/index.min' {
  declare module.exports: any;
}

declare module '@tippy.js/react/umd' {
  declare module.exports: any;
}

declare module '@tippy.js/react/umd/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tippy.js/react/esm/index' {
  declare module.exports: $Exports<'@tippy.js/react/esm'>;
}
declare module '@tippy.js/react/esm/index.js' {
  declare module.exports: $Exports<'@tippy.js/react/esm'>;
}
declare module '@tippy.js/react/esm/index.min.js' {
  declare module.exports: $Exports<'@tippy.js/react/esm/index.min'>;
}
declare module '@tippy.js/react/umd/index' {
  declare module.exports: $Exports<'@tippy.js/react/umd'>;
}
declare module '@tippy.js/react/umd/index.js' {
  declare module.exports: $Exports<'@tippy.js/react/umd'>;
}
declare module '@tippy.js/react/umd/index.min.js' {
  declare module.exports: $Exports<'@tippy.js/react/umd/index.min'>;
}
