import { batchFormFragment, batchCardFragment, batchCardWithOwnedFragment } from './batch/fragment';
import {
  itemFormFragment,
  itemCardFragment,
  itemCardWithOwnedFragment,
  itemInSelectorFragment,
  itemInOrderFormFragment,
  itemInBatchFormFragment,
} from './item/fragment';
import {
  orderFormFragment,
  orderFormQueryFragment,
  orderCardFragment,
  orderCardWithOwnedFragment,
} from './order/fragment';
import { partnerFormFragment, partnerCardFragment } from './partner/fragment';
import {
  productFormFragment,
  productCardFragment,
  productCardWithOwnedFragment,
} from './product/fragment';
import {
  containerFormFragment,
  containerCardFragment,
  containerCardWithOwnedFragment,
} from './container/fragment';
import {
  productProviderFormFragment,
  productProviderPackagingFragment,
  productProviderCardFragment,
} from './productProvider/fragment';
import {
  shipmentFormFragment,
  shipmentFormQueryFragment,
  shipmentCardFragment,
  shipmentCardWithOwnedFragment,
} from './shipment/fragment';
import { staffFormFragment, staffCardFragment } from './staff/fragment';
import { tagFormFragment, tagCardFragment } from './tag/fragment';
import { warehouseFormFragment, warehouseCardFragment } from './warehouse/fragment';
import {
  milestoneFragment,
  milestoneCardFragment,
  milestoneFormFragment,
  projectCardFragment,
  projectCardNewFragment,
  projectFormQueryFragment,
  projectFormFragment,
} from './project/fragment';
import {
  taskCardFragment,
  taskTemplateCardFragment,
  taskWithoutParentInfoFragment,
  taskWithParentInfoFragment,
  taskTemplateFormFragment,
  taskFormInTemplateFragment,
  taskCountFragment,
} from './task/fragment';
import { tableTemplateCardFragment } from './tableTemplate/fragment';
import { badRequestFragment, notFoundFragment, forbiddenFragment } from './errors/fragment';
import {
  metricFragment,
  sizeFragment,
  priceFragment,
  tagFragment,
  imageFragment,
  documentFragment,
  userAvatarFragment,
  partnerNameFragment,
  timelineDateFullFragment,
  timelineDateMinimalFragment,
  portFragment,
  customFieldsFragment,
  maskFragment,
  fieldValuesFragment,
  fieldDefinitionFragment,
  ownedByFragment,
} from './common/fragment';

export {
  batchFormFragment,
  batchCardFragment,
  batchCardWithOwnedFragment,
  containerFormFragment,
  containerCardFragment,
  containerCardWithOwnedFragment,
  itemFormFragment,
  itemCardFragment,
  itemCardWithOwnedFragment,
  itemInSelectorFragment,
  itemInOrderFormFragment,
  itemInBatchFormFragment,
  orderFormFragment,
  orderFormQueryFragment,
  orderCardFragment,
  orderCardWithOwnedFragment,
  partnerFormFragment,
  partnerCardFragment,
  productFormFragment,
  productCardFragment,
  productCardWithOwnedFragment,
  productProviderFormFragment,
  productProviderPackagingFragment,
  productProviderCardFragment,
  shipmentFormQueryFragment,
  shipmentFormFragment,
  shipmentCardFragment,
  shipmentCardWithOwnedFragment,
  staffFormFragment,
  staffCardFragment,
  tagFormFragment,
  tagCardFragment,
  taskWithoutParentInfoFragment,
  taskWithParentInfoFragment,
  taskTemplateFormFragment,
  taskFormInTemplateFragment,
  warehouseFormFragment,
  warehouseCardFragment,
  metricFragment,
  sizeFragment,
  priceFragment,
  tagFragment,
  imageFragment,
  documentFragment,
  userAvatarFragment,
  partnerNameFragment,
  timelineDateFullFragment,
  timelineDateMinimalFragment,
  portFragment,
  tableTemplateCardFragment,
  customFieldsFragment,
  maskFragment,
  fieldValuesFragment,
  fieldDefinitionFragment,
  badRequestFragment,
  notFoundFragment,
  forbiddenFragment,
  ownedByFragment,
  projectCardFragment,
  milestoneFragment,
  milestoneFormFragment,
  milestoneCardFragment,
  projectCardNewFragment,
  projectFormQueryFragment,
  projectFormFragment,
  taskCardFragment,
  taskTemplateCardFragment,
  taskCountFragment,
};
