name: "PR Checks"
on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install --non-interactive --no-progress --frozen-lockfile --ignore-optional

      - name: Run tests
        run: yarn test
        env:
          CI: true

  deploy_now:
    name: Deploy PR on now
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install --non-interactive --no-progress --frozen-lockfile --ignore-optional

      - name: Build
        run: yarn build:stg

      - name: Deploy to now
        uses: zenportinc/deploy-now-action@v1-release
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-dir: ${{ format('{0}/{1}', runner.workspace, 'web-app') }}
          build-dir: 'build'
